services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DATABASE=avito
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
  dbgrpc:
    restart: always
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DATABASE=avitogrpc
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
  httpserver:
    image: http-server-image:latest
    build:
      context: ./httpserver
    ports:
      - "3000:3000"
  grpcserver:
    image: grpc-server-image:latest
    build:
      context: ./grpcserver
    ports:
      - "8080:8080"
volumes:
  db:
  dbgrpc:
  httpserver:
  grpcserver: