env: "local"

database:
  host: "localhost"
  port: "5435"
  user: "postgres"
  dbname: "avito"
  max_attempts: 5

servers:
  http:
    port: "8080"
    host: "0.0.0.0"
    timeout: 4s
    idle_timeout: 60s