services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=avito
      - POSTGRES_USER=postgres
  dbgrpc:
    restart: always
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=avito
      - POSTGRES_USER=postgres
#  httpserver:
#    image: http-server-image:latest
#    build:
#      context: ./golang-avito-http
#    ports:
#      - "3000:3000"
#  grpcserver:
#    image: grpc-server-image:latest
#    build:
#      context: ./golang-avito-grpc
#    ports:
#      - "8080:8080"
volumes:
  dbhttp:
  dbgrpc:
#  httpserver:
#  grpcserver: